### ISSUE TITLE
Support for Username and Password as Non-uri Configuration

### ISSUE THREAD

**Issue by bdrillard** [agrison/duct-mongodb#1]
Currently providing user credentials is only possible via URI parameters:

```edn
{:duct.database.mongodb/monger 
  {:uri "mongodb://127.0.0.1:27017/hello?username=foo&password=bar"}
```

In some instances, an environment may more easily be able to inject these values separately. Could we add optional keys to the configuration map to support connecting with basic credentials? E.g.

```edn
{:duct.database.mongodb/monger 
  {:host "127.0.0.1", :port 27017, :db-name "hello" :username "user" :password "pass"}}
```

I think the passive changes to the `init-key` would be pretty straightforward given the clear Monger support for basic [authentication](http://clojuremongodb.info/articles/connecting.html#authentication). I'm happy to submit a PR.

**Comment by agrison** [comment]
You can of course submit a PR this is a great idea 👍

**Comment by bdrillard** [comment]
Can a new release be cut now that this has been merged?

**Comment by agrison** [comment]
It has been released
https://clojars.org/me.grison/duct-mongodb/versions/0.1.2
